# Site settings
title: CLI Gem Scraper
header-img: img/home-bg.png
email: gusvilla303@gmail.com
copyright_name: GusVilla303
description: > # this means to ignore newlines until "baseurl:"
  Scrape NPR Featured Stories
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: gusvilla303
github_username:  GusVilla303
learn_profile: GusVilla303
email_username: gusvilla303@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
